"""The deployment manifest: one artifact pinning what a node must run.

See ``docs/superpowers/specs/2026-09-16-nimble-factory-design.md``, section
A.6. This exists because three separate drift incidents were found by hand
in one session, and no automated signal reported any of them: a binary
(skmail) that belonged to no package so no version check could see it, a
seat unit that sat FAILED for weeks, and two hosts sitting two merged PRs
behind main. Throughout all three, ``pip show`` and the module's
``__version__`` agreed on every host. A controller that only checked
versions would have reported the fleet healthy.

``required_env`` is the one field that has already failed by hand three
times (A.6). It is never typed here: it is generated by AST-walking the
dispatcher source, reusing ``scripts/fleet/skfleet_readiness.required_env``
rather than re-implementing the walk as a second copy that can drift from
the first.

``revision`` is a content digest, not a timestamp. The A.6 example shows a
timestamp, but Task 3 (drift detection) compares manifests for equality, and
a wall-clock timestamp would make two manifests built seconds apart from the
exact same repository state compare unequal for no reason. ``revision`` is
``sha256`` of the canonical JSON of the other four fields, so identical
inputs really do produce an identical manifest, field for field, including
``revision`` itself.
"""

from __future__ import annotations

import hashlib
import importlib.util
import json
import os
import subprocess
import tempfile
from pathlib import Path
from typing import Any

DISPATCHER_RELATIVE_PATH = Path("scripts") / "fleet" / "skfleet-rotate.py"
WORKER_WRAPPER_RELATIVE_PATH = Path("scripts") / "fleet" / "skfleet-worker-wrapper.py"
READINESS_GATE_RELATIVE_PATH = Path("scripts") / "fleet" / "skfleet_readiness.py"
CANONICAL_SYSTEMD_RELATIVE_DIR = Path("systemd")

#: Where a rollout copies per-host artifacts, relative to the node's home.
#: This is NOT ``~/.skenv/bin`` (where pip installs every ``script-files``
#: entry as a side effect of ``pip install -e .``): it is the separate,
#: explicitly-copied location the live units actually execute from, measured
#: on chiap01/02/03/04/08.
PER_HOST_BIN_RELATIVE_DIR = Path(".local") / "bin"

#: Every artifact a rollout must copy into ``PER_HOST_BIN_RELATIVE_DIR`` on
#: each node, declared exactly ONCE so a rollout, a rollback, and the drift
#: detector cannot disagree about what "deployed" means.
#:
#: Why the worker wrapper belongs here and why leaving it out was a latent
#: outage: ``scripts/fleet/skfleet-rotate.py`` resolves its wrapper as
#: ``os.path.join(os.path.dirname(__file__), "skfleet-worker-wrapper.py")``
#: -- next to ITSELF, not by PATH lookup and not from the installed package.
#: The dispatcher that actually runs is the deployed copy at
#: ``~/.local/bin/skfleet-rotate.py`` (confirmed live: every chi host's
#: ``skfleet-rotate.service`` ExecStart names that path), so the wrapper
#: that actually runs is ``~/.local/bin/skfleet-worker-wrapper.py``.
#:
#: The rollout previously copied only the dispatcher. The wrapper at that
#: path was current only because ``pip install -e .`` happens to also place
#: it in ``~/.skenv/bin`` and someone had, at some point, copied a matching
#: file to ``~/.local/bin`` by hand. Nothing kept them equal. The first
#: wrapper change after a rollout would have shipped a NEW dispatcher
#: calling an OLD wrapper, with no step in any code path to correct it and
#: no check to report it -- the same shape as the one-hour fleet outage on
#: 2026-09-19, where a deploy did ``git pull`` and copied the dispatcher but
#: skipped ``pip install -e .``.
#:
#: Adding a per-host artifact later means adding one entry HERE. Everything
#: that copies or grades these files derives from this tuple.
#: ``skwork-sweep.py`` is here for a second, independent reason: it is
#: declared in NO package at all. It is not a ``script-files`` entry, so pip
#: never installs it and section 2b of ``rollout_drift`` cannot see it,
#: exactly like the skmail incident that module's docstring records (three
#: different binaries across five hosts, invisible because the file belonged
#: to no package). It is nevertheless deployed to ``~/.local/bin`` and run by
#: a live systemd unit on all five chi hosts. Declaring it HERE, rather than
#: in ``script-files``, is deliberate: ``script-files`` would make pip place
#: a second copy in ``~/.skenv/bin`` that no host has today, so every host
#: would immediately report a spurious ``script:`` missing finding. This is
#: the list of things the ROLLOUT deploys, which is the true statement.
PER_HOST_ARTIFACTS: tuple[Path, ...] = (
    DISPATCHER_RELATIVE_PATH,
    WORKER_WRAPPER_RELATIVE_PATH,
    Path("scripts") / "fleet" / "skwork-sweep.py",
)

_MANIFEST_FIELDS = ("git_sha", "package_version", "required_env", "units")


def deployed_artifact_path(name: str, home: Path | str | None = None) -> Path:
    """Where a per-host artifact ACTUALLY lives on a node.

    ``name`` is a basename from ``PER_HOST_ARTIFACTS`` (e.g.
    ``"skfleet-rotate.py"``).

    Every one of these scripts exists at TWO paths on a live host, placed by
    two unrelated mechanisms:

      ``~/.skenv/bin/<name>``   a side effect of ``pip install -e .``, because
                                the script is a ``script-files`` entry.
      ``~/.local/bin/<name>``   an explicit ``cp`` in the rollout's deploy
                                step. This is the one the units execute:
                                confirmed live on chiap01/02/03/04/08, whose
                                ``skfleet-rotate.service`` ExecStart names it.

    Nothing keeps the two equal. Today they happen to match on all five
    hosts, so a caller that guessed wrong has been getting the right answer
    by luck; the first rollout that copies one and not the other makes the
    guess wrong with no error and no report.

    Callers must NEVER derive this from ``Path(sys.executable).parent``.
    That resolves to ``~/.skenv/bin`` -- the pip copy, not the deployed one
    -- and it fails in the most expensive way available: the wrong file
    EXISTS, so an ``is_file()`` guard passes and a stale dispatcher runs
    silently, instead of failing closed the way a missing file would.
    """
    base = Path(home) if home is not None else Path.home()
    return base / PER_HOST_BIN_RELATIVE_DIR / name


def _canonical_json(value: Any) -> bytes:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode()


def _revision_for(manifest: dict[str, Any]) -> str:
    """Content digest over the four pinned fields, excluding revision itself.

    Any extra keys a caller may have added are excluded too, since revision
    is defined as a digest of exactly the A.6 fields, not of whatever a
    mutated copy happens to carry.
    """
    body = {name: manifest[name] for name in _MANIFEST_FIELDS}
    return hashlib.sha256(_canonical_json(body)).hexdigest()


def _load_readiness_required_env(repo_root: Path, dispatcher_source: str) -> list[str]:
    """Call skfleet_readiness.required_env without duplicating its AST walk.

    scripts/fleet/skfleet_readiness.py is a standalone script, not a package
    module (it is excluded from the sdist/wheel package data, see
    pyproject.toml), so it cannot be imported by dotted name. It has no
    imports of its own beyond the standard library, so it is loaded straight
    from the file the same repository checkout ships, by path, without
    registering it in sys.modules (it needs no package context to run).
    """
    gate_path = repo_root / READINESS_GATE_RELATIVE_PATH
    spec = importlib.util.spec_from_file_location("skfleet_readiness", gate_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"could not load the readiness gate module from {gate_path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return sorted(module.required_env(dispatcher_source))


def _git_sha(repo_root: Path) -> str:
    result = subprocess.run(
        ["git", "-C", str(repo_root), "rev-parse", "--short=8", "HEAD"],
        capture_output=True,
        text=True,
        check=False,
    )
    sha = result.stdout.strip()
    if result.returncode != 0 or not sha:
        raise RuntimeError(
            f"could not resolve the git HEAD of {repo_root}: "
            f"{result.stderr.strip() or 'no output'}"
        )
    return sha


def _package_version() -> str:
    """The version of the skcapstone distribution actually installed here.

    Reuses the single source of truth skcapstone.__init__ already
    establishes (installed dist-info metadata, falling back to reading the
    git tag directly in an uninstalled checkout), rather than a second
    lookup that could disagree with ``skcapstone --version``.
    """
    from skcapstone import __version__

    return __version__


def _shipped_units(repo_root: Path) -> list[str]:
    """Every *.service unit actually shipped, not a hand-maintained list.

    Read from the canonical systemd/ tree. A repository-level test
    (test_systemd.py::TestUnitTreeSingleSourceOfTruth) asserts that tree
    stays byte-identical to src/skcapstone/data/systemd/, the tree that
    ships in the wheel, so either is a faithful source here; the canonical
    tree is used because it is guaranteed present in the checkout that also
    supplies git_sha and required_env.
    """
    units_dir = repo_root / CANONICAL_SYSTEMD_RELATIVE_DIR
    names = sorted(path.name for path in units_dir.glob("*.service"))
    if not names:
        raise RuntimeError(f"no *.service unit files found under {units_dir}")
    return names


def build_manifest(repo_root: Path | str, home: Path | str) -> dict[str, Any]:
    """Build the deployment manifest for the checkout at ``repo_root``.

    Args:
        repo_root: A git checkout containing ``scripts/fleet/`` and the
            canonical ``systemd/`` tree. Every field but ``package_version``
            is derived from this checkout, read-only.
        home: The estate home. Accepted for interface symmetry with
            ``detect_drift(manifest, home, repo_root)`` (Task 3), which
            reads a live node's *installed* state under home to compare
            against this manifest. Building the manifest itself needs no
            per-node state: git_sha and required_env come from the repo
            checkout, package_version from the running interpreter's
            installed distribution, and units from the shipped systemd
            tree. None of those are home-scoped, so home is not consulted
            here; it is threaded through only so both halves of the
            manifest pipeline share one calling convention.

    Returns:
        A dict with exactly the five A.6 fields: revision, git_sha,
        package_version, required_env, units.
    """
    repo_root = Path(repo_root)
    Path(home)  # accepted for signature symmetry; see docstring above.

    dispatcher_path = repo_root / DISPATCHER_RELATIVE_PATH
    dispatcher_source = dispatcher_path.read_text(encoding="utf-8")

    manifest: dict[str, Any] = {
        "git_sha": _git_sha(repo_root),
        "package_version": _package_version(),
        "required_env": _load_readiness_required_env(repo_root, dispatcher_source),
        "units": _shipped_units(repo_root),
    }
    manifest["revision"] = _revision_for(manifest)
    return {
        "revision": manifest["revision"],
        "git_sha": manifest["git_sha"],
        "package_version": manifest["package_version"],
        "required_env": manifest["required_env"],
        "units": manifest["units"],
    }


def write_manifest(path: Path | str, manifest: dict[str, Any]) -> None:
    """Write ``manifest`` atomically: tmp file in the same directory, then
    ``os.replace``, matching ``skcapstone.lifecycle_seats._atomic_write``.

    Other processes read this path (the readiness gate, drift detection), so
    a reader never observes a partially-written file: the temp file is
    either fully written and fsynced, or the rename has not happened yet and
    the previous file (or nothing) is still what a reader sees.
    """
    path = Path(path)
    payload = _canonical_json(manifest) + b"\n"

    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temp_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "wb") as stream:
            stream.write(payload)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temp_name, path)
    except BaseException:
        Path(temp_name).unlink(missing_ok=True)
        raise
