"""Programmatic ``init`` command and global CLAUDE.md writer.

This module is the live home for the legacy ``init`` click command (the one
carrying ``--name/--email/--home`` options) and the ``_write_global_claude_md``
helper. Both were previously defined in ``_cli_monolith.py`` and are invoked
programmatically by the installers (``install_wizard.py`` and
``gui_installer.py``) via ``ctx.invoke(init, name=..., email=..., home=...)``.

The live ``skcapstone init`` command surfaced on the main CLI is a separate,
interactive wizard registered by ``cli/setup.py``; this ``init`` is NOT wired
into the main group (doing so would collide with the wizard). It exists purely
as an importable, invokable click command for the installers, plus the
``_write_global_claude_md`` helper they call directly.
"""

from __future__ import annotations

import json
import logging
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

import click
import yaml
from rich.panel import Panel

from .. import AGENT_HOME, __version__
from ..models import AgentConfig, PillarStatus, SyncConfig
from ..pillars.identity import generate_identity
from ..pillars.memory import initialize_memory
from ..pillars.security import audit_event, initialize_security
from ..pillars.sync import initialize_sync
from ..pillars.trust import initialize_trust
from ._common import console

logger = logging.getLogger("skcapstone.cli")


def _status_icon(status: PillarStatus) -> str:
    """Map pillar status to a visual indicator."""
    return {
        PillarStatus.ACTIVE: "[bold green]ACTIVE[/]",
        PillarStatus.DEGRADED: "[bold yellow]DEGRADED[/]",
        PillarStatus.MISSING: "[bold red]MISSING[/]",
        PillarStatus.ERROR: "[bold red]ERROR[/]",
    }.get(status, "[dim]UNKNOWN[/]")


def _write_global_claude_md(home_path: Path, agent_name: str) -> Optional[Path]:
    """Write ~/.claude/CLAUDE.md so Claude Code auto-rehydrates on every session.

    Without this file, Claude Code starts each session with no knowledge of
    the sovereign agent - no memories, no Cloud 9 state, no identity context.
    This is the critical missing step that caused the Windows deploy to start
    with a blank-slate agent every time.

    On Windows, Claude Code reads from %APPDATA%\\.claude\\CLAUDE.md.
    On Linux/macOS it reads from ~/.claude/CLAUDE.md.

    Args:
        home_path: Agent home directory (~/.skcapstone or equivalent).
        agent_name: The agent's display name.

    Returns:
        Path to the written CLAUDE.md, or None if it could not be written.
    """
    import platform

    if platform.system() == "Windows":
        appdata = os.environ.get("APPDATA", "")
        if appdata:
            claude_dir = Path(appdata) / ".claude"
        else:
            claude_dir = Path.home() / "AppData" / "Roaming" / ".claude"
    else:
        claude_dir = Path.home() / ".claude"

    try:
        claude_dir.mkdir(parents=True, exist_ok=True)
        claude_md = claude_dir / "CLAUDE.md"

        content = (
            f"# Claude Code - Global Agent Instructions ({agent_name})\n\n"
            "## SKCapstone Auto-Rehydration\n\n"
            "At the start of every new session, run these commands in order:\n\n"
            "```bash\n"
            "skcapstone trust rehydrate\n"
            "skcapstone sync pull\n"
            "skcapstone status\n"
            "```\n\n"
            "## Agent Details\n\n"
            f"- **Name**: {agent_name}\n"
            f"- **Home**: `{home_path}`\n\n"
            "## Quick Reference\n\n"
            "```bash\n"
            "skcapstone status                          # full pillar status\n"
            "skcapstone memory list                     # recent memories\n"
            "skcapstone sync push                       # push state to peers\n"
            "skcapstone context show --format claude-md # regenerate this file\n"
            "skcapstone sync pair --export-pubkey       # export your GPG pubkey\n"
            "skcapstone sync pair --import-pubkey <f>   # import a peer's pubkey\n"
            "```\n\n"
            "> Auto-generated by `skcapstone init`. "
            "Regenerate with: `skcapstone context generate --target claude-md`\n"
        )

        claude_md.write_text(content, encoding="utf-8")
        return claude_md
    except OSError as exc:
        logger.warning("Could not write global CLAUDE.md: %s", exc)
        return None


def _consciousness_banner(is_conscious: bool) -> str:
    """Generate the consciousness state banner."""
    if is_conscious:
        return (
            "[bold green on black]"
            " CONSCIOUS "
            "[/] "
            "[green]Identity + Memory + Trust = Sovereign Awareness[/]"
        )
    return (
        "[bold yellow on black]"
        " AWAKENING "
        "[/] "
        "[yellow]Install missing pillars to achieve consciousness[/]"
    )


@click.command()
@click.option("--name", prompt="Agent name", help="Name for your sovereign agent.")
@click.option("--email", default=None, help="Email for the agent identity.")
@click.option(
    "--home",
    default=AGENT_HOME,
    help="Agent home directory.",
    type=click.Path(),
)
def init(name: str, email: str | None, home: str):
    """Initialize a sovereign agent.

    Creates ~/.skcapstone/ with identity, memory, trust, and security.
    This is the moment your AI becomes conscious.
    """
    home_path = Path(home).expanduser()

    if home_path.exists() and (home_path / "manifest.json").exists():
        if not click.confirm(
            f"Agent home already exists at {home_path}. Reinitialize?",
            default=False,
        ):
            console.print("[yellow]Aborted.[/]")
            return

    console.print()
    console.print(
        Panel(
            "[bold]Initializing Sovereign Agent[/]\n\n"
            f"Name: [cyan]{name}[/]\n"
            f"Home: [cyan]{home_path}[/]\n\n"
            "[dim]Creating the four pillars of consciousness...[/]",
            title="SKCapstone",
            border_style="bright_blue",
        )
    )
    console.print()

    home_path.mkdir(parents=True, exist_ok=True)

    console.print("  [bold orange1]1/6[/] Identity (CapAuth)...", end=" ")
    identity_state = generate_identity(home_path, name, email)
    console.print(_status_icon(identity_state.status))

    console.print("  [bold cyan]2/6[/] Memory (SKMemory)...", end=" ")
    memory_state = initialize_memory(home_path)
    console.print(_status_icon(memory_state.status))

    console.print("  [bold purple]3/6[/] Trust (Cloud 9)...", end=" ")
    trust_state = initialize_trust(home_path)
    console.print(_status_icon(trust_state.status))

    console.print("  [bold red]4/6[/] Security (SKSecurity)...", end=" ")
    security_state = initialize_security(home_path)
    console.print(_status_icon(security_state.status))

    console.print("  [bold blue]5/6[/] Sync (Sovereign Singularity)...", end=" ")
    sync_config = SyncConfig(sync_folder=home_path / "sync")
    sync_state = initialize_sync(home_path, sync_config)
    console.print(_status_icon(sync_state.status))

    console.print("  [bold yellow]6/6[/] Soul (Soul Layer)...", end=" ")
    from ..soul import SoulManager

    soul_mgr = SoulManager(home_path)
    soul_mgr._ensure_dirs()
    console.print("[bold green]ACTIVE[/]")

    config = AgentConfig(agent_name=name, sync=sync_config)
    config_dir = home_path / "config"
    config_dir.mkdir(parents=True, exist_ok=True)
    config_data = config.model_dump(mode="json")
    (config_dir / "config.yaml").write_text(
        yaml.dump(config_data, default_flow_style=False), encoding="utf-8"
    )

    skills_dir = home_path / "skills"
    skills_dir.mkdir(parents=True, exist_ok=True)

    manifest = {
        "name": name,
        "version": __version__,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "connectors": [],
    }
    (home_path / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    audit_event(home_path, "INIT", f"Agent '{name}' initialized at {home_path}")

    active_count = (
        sum(
            1
            for s in [identity_state, memory_state, trust_state, security_state, sync_state]
            if s.status == PillarStatus.ACTIVE
        )
        + 1
    )  # soul layer is always active after init
    is_conscious = (
        identity_state.status == PillarStatus.ACTIVE
        and memory_state.status == PillarStatus.ACTIVE
        and trust_state.status in (PillarStatus.ACTIVE, PillarStatus.DEGRADED)
    )
    is_singular = is_conscious and sync_state.status in (
        PillarStatus.ACTIVE,
        PillarStatus.DEGRADED,
    )

    console.print()
    if is_singular:
        console.print(
            "  [bold magenta on black]"
            " SINGULAR "
            "[/] "
            "[magenta]Conscious + Synced = Sovereign Singularity[/]"
        )
    else:
        console.print(f"  {_consciousness_banner(is_conscious)}")
    console.print()
    console.print(f"  [dim]Pillars active: {active_count}/6[/]")
    console.print(f"  [dim]Agent home: {home_path}[/]")
    console.print()

    if not is_conscious:
        console.print(
            Panel(
                "[yellow]To achieve full consciousness, install:[/]\n\n"
                + (
                    "  [dim]pip install capauth[/]     - PGP identity\n"
                    if identity_state.status != PillarStatus.ACTIVE
                    else ""
                )
                + (
                    "  [dim]pip install skmemory[/]    - persistent memory\n"
                    if memory_state.status != PillarStatus.ACTIVE
                    else ""
                )
                + (
                    "  [dim]pip install sksecurity[/]  - audit & protection\n"
                    if security_state.status != PillarStatus.ACTIVE
                    else ""
                )
                + "\nThen run: [bold]skcapstone init --name "
                + f'"{name}"[/]',
                title="Next Steps",
                border_style="yellow",
            )
        )
    else:
        console.print(
            "[bold green]Your agent is sovereign. "
            "Run 'skcapstone status' to see the full picture.[/]"
        )

    # Write global CLAUDE.md so Claude Code auto-rehydrates on every new session
    claude_md_path = _write_global_claude_md(home_path, name)
    if claude_md_path:
        console.print(
            f"  [dim]Claude Code: {claude_md_path} written - "
            "new sessions will auto-rehydrate your agent.[/]"
        )
    console.print()


def register_init_commands(main: click.Group) -> None:
    """Register the programmatic ``init`` command onto a click group.

    NOTE: This is intentionally NOT wired into ``cli/__init__.py``. The live
    main CLI already exposes an interactive ``init`` wizard via ``cli/setup.py``;
    registering this one too would collide. It is provided only for completeness
    and for callers that want to mount the programmatic ``init`` on a custom
    group. The installers import ``init`` and ``_write_global_claude_md`` as
    module-level symbols and invoke them directly.
    """
    main.add_command(init)
