#!/usr/bin/env bash
# Revert the node-100 unit slim. Generated by
# scripts/fleet/gen-node-disposition.py. Do not hand-edit.
#
# Re-enables exactly the units the disposition plan disables, and
# nothing else. Every step in this epic owes a documented revert.
set -euo pipefail

systemctl --user enable session-migration.service
systemctl --user enable skvoice.service

echo "reverted 2 unit(s) on node-100"
