#!/usr/bin/env bash
# Validate the version generated by setuptools-scm without requiring a manifest.
set -euo pipefail

PY_VER=$(python - <<'PY'
from pathlib import Path
import tomllib

project = tomllib.loads(Path("pyproject.toml").read_text())['project']
if 'version' not in project.get('dynamic', []):
    raise SystemExit("pyproject.toml must declare a dynamic version")
try:
    from setuptools_scm import get_version
    version = get_version(root='.')
except Exception as exc:
    raise SystemExit(f"unable to resolve setuptools-scm version: {exc}")
if not version:
    raise SystemExit("setuptools-scm returned an empty version")
print(version)
PY
)

if [[ -f package.json ]]; then
    JS_VER=$(python -c "import json; print(json.load(open('package.json'))['version'])")
    if [[ "$PY_VER" != "$JS_VER" ]]; then
        echo "FAIL: Version mismatch - setuptools-scm=$PY_VER package.json=$JS_VER" >&2
        exit 1
    fi
    echo "OK: setuptools-scm ($PY_VER) == package.json ($JS_VER)"
else
    echo "OK: setuptools-scm generated version ($PY_VER); no package.json to compare"
fi
