"""Tests for the deployment manifest (spec A.6).

The manifest is the one artifact pinning what a node must run. Three real
drift incidents (skmail's file belonging to no package, a FAILED seat unit
that lingered for weeks, and two hosts sitting behind on merged commits) all
slipped past version checks because ``pip show`` and ``__version__`` agreed
on every host throughout. These tests hold the manifest to the two things
that actually catch that class of drift: ``required_env`` must come from the
same AST walk the readiness gate uses (never a hand-typed list), and
building the manifest twice from identical inputs must not itself introduce
drift between two otherwise-identical snapshots.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]

sys.path.insert(0, str(REPO_ROOT / "scripts" / "fleet"))
from skfleet_readiness import required_env as readiness_required_env  # noqa: E402

from skcapstone.fleet.deployment_manifest import build_manifest, write_manifest  # noqa: E402

DISPATCHER_PATH = REPO_ROOT / "scripts" / "fleet" / "skfleet-rotate.py"


@pytest.fixture
def home(tmp_path: Path) -> Path:
    """A throwaway estate home, never the real ~/.skcapstone."""
    return tmp_path / "home"


def test_manifest_carries_all_five_fields(home: Path) -> None:
    manifest = build_manifest(REPO_ROOT, home)
    assert set(manifest) == {
        "revision",
        "git_sha",
        "package_version",
        "required_env",
        "units",
    }
    assert isinstance(manifest["revision"], str) and manifest["revision"]
    assert isinstance(manifest["git_sha"], str) and manifest["git_sha"]
    assert isinstance(manifest["package_version"], str) and manifest["package_version"]
    assert isinstance(manifest["required_env"], list) and manifest["required_env"]
    assert isinstance(manifest["units"], list) and manifest["units"]


def test_required_env_matches_the_readiness_gate_exactly(home: Path) -> None:
    """required_env must be generated by skfleet_readiness, never typed by hand."""
    manifest = build_manifest(REPO_ROOT, home)
    dispatcher_source = DISPATCHER_PATH.read_text(encoding="utf-8")
    expected = sorted(readiness_required_env(dispatcher_source))
    assert manifest["required_env"] == expected
    # And it must be a real, non-trivial result, not an accidentally-empty walk.
    assert expected


def test_units_come_from_the_shipped_systemd_tree_not_a_hardcoded_list(home: Path) -> None:
    manifest = build_manifest(REPO_ROOT, home)
    shipped = sorted(p.name for p in (REPO_ROOT / "systemd").glob("*.service"))
    assert manifest["units"] == shipped


def test_git_sha_matches_the_real_repository_head(home: Path) -> None:
    import subprocess

    manifest = build_manifest(REPO_ROOT, home)
    result = subprocess.run(
        ["git", "-C", str(REPO_ROOT), "rev-parse", "--short=8", "HEAD"],
        capture_output=True,
        text=True,
        check=True,
    )
    assert manifest["git_sha"] == result.stdout.strip()


def test_building_twice_from_identical_inputs_is_byte_identical(home: Path) -> None:
    """Two manifests built from the same repo state must compare equal.

    Task 3 compares manifests for equality to detect drift. A revision that
    is a wall-clock timestamp would make two manifests built seconds apart
    from the exact same commit differ for no reason, defeating that
    comparison. revision here is a content digest of the other four fields,
    so identical inputs really do produce an identical manifest, field for
    field, including revision.
    """
    first = build_manifest(REPO_ROOT, home)
    second = build_manifest(REPO_ROOT, home)
    assert first == second
    assert json.dumps(first, sort_keys=True) == json.dumps(second, sort_keys=True)


def test_revision_changes_when_the_manifest_content_changes(home: Path) -> None:
    """A content-digest revision must actually respond to content changes,
    or it would be a constant pretending to be a digest."""
    manifest = build_manifest(REPO_ROOT, home)
    mutated = dict(manifest)
    mutated["units"] = [*manifest["units"], "not-a-real-unit.service"]

    from skcapstone.fleet.deployment_manifest import _revision_for

    assert _revision_for(mutated) != manifest["revision"]


def test_write_manifest_is_atomic_and_leaves_no_temp_file(tmp_path: Path, home: Path) -> None:
    manifest = build_manifest(REPO_ROOT, home)
    target = tmp_path / "deployment-manifest.json"

    write_manifest(target, manifest)

    assert target.is_file()
    assert json.loads(target.read_text(encoding="utf-8")) == manifest
    leftovers = [p for p in tmp_path.iterdir() if p != target]
    assert leftovers == [], f"temp file left behind by write_manifest: {leftovers}"


def test_write_manifest_uses_tmp_plus_os_replace_in_the_same_directory(
    tmp_path: Path, home: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    import os

    manifest = build_manifest(REPO_ROOT, home)
    target = tmp_path / "nested" / "deployment-manifest.json"

    calls: list[tuple[str, str]] = []
    real_replace = os.replace

    def spy_replace(src, dst):
        calls.append((str(src), str(dst)))
        return real_replace(src, dst)

    monkeypatch.setattr(os, "replace", spy_replace)

    write_manifest(target, manifest)

    assert len(calls) == 1
    src, dst = calls[0]
    assert dst == str(target)
    assert Path(src).parent == target.parent


def test_write_manifest_twice_with_identical_manifest_yields_identical_bytes(
    tmp_path: Path, home: Path
) -> None:
    manifest = build_manifest(REPO_ROOT, home)
    target = tmp_path / "deployment-manifest.json"

    write_manifest(target, manifest)
    first_bytes = target.read_bytes()
    write_manifest(target, build_manifest(REPO_ROOT, home))
    second_bytes = target.read_bytes()

    assert first_bytes == second_bytes
